/**
 * The regions of the 1651 frontispiece, as fractions of the plate (percent
 * from the top-left corner), each with what the engraving shows there and,
 * where the site has a page about it, where to read on.
 *
 * The engraving is by Abraham Bosse, made in Paris with Hobbes at his elbow.
 * The two columns of panels are its argument in pictures: every instrument of
 * the civil power on the left has its ecclesiastical double on the right, and
 * one figure holds the emblems of both.
 */
export interface Region {
  id: string;
  title: string;
  /** civil (left column), church (right column), or neither. */
  side?: "civil" | "church";
  /** Percentages of the plate: left, top, width, height. */
  x: number;
  y: number;
  w: number;
  h: number;
  note: string;
  href?: string;
  hrefLabel?: string;
}

export const REGIONS: Region[] = [
  {
    id: "motto",
    title: "The motto",
    x: 0.5,
    y: 0.2,
    w: 99,
    h: 2.6,
    note: "Non est potestas Super Terram quae Comparetur ei. Iob. 41.24 — there is no power on earth to be compared to him. God's description of the sea monster Leviathan, from the same chapter of Job that gives the book its title; the verse never appears in the text beneath it.",
    href: "/latin/#non-est-potestas-super-terram-quae-comparetur-ei",
    hrefLabel: "In the Latin glossary",
  },
  {
    id: "head",
    title: "The head and the crown",
    x: 34.5,
    y: 2.6,
    w: 20,
    h: 12,
    note: "A particular, mortal face under the crown: the artificial man has a natural man at the top, because a commonwealth acts only through the person who bears it. Readers have tried to put a name to the face since 1651 — Charles I, Cromwell, Hobbes himself — and the engraving declines to settle it.",
    href: "/concepts/sovereign/",
    hrefLabel: "The sovereign",
  },
  {
    id: "body",
    title: "The body",
    x: 21.5,
    y: 12,
    w: 42,
    h: 17.5,
    note: "More than three hundred small figures with their backs to us, every face turned toward the head. The multitude united in one person — the picture shows what the state is made of: us. In the manuscript copy presented to Charles II the bodies are heads instead, looking out at the reader.",
    href: "/concepts/person/",
    hrefLabel: "Person",
  },
  {
    id: "sword",
    title: "The sword",
    side: "civil",
    x: 2,
    y: 2.6,
    w: 19,
    h: 28,
    note: "The civil power, raised in the right hand: the sword of justice and of defence, and the reason covenants hold — covenants, without the sword, are but words. Everything in the left column of panels below belongs to it.",
    href: "/themes/sovereignty/",
    hrefLabel: "Sovereignty",
  },
  {
    id: "crozier",
    title: "The crozier",
    side: "church",
    x: 55.5,
    y: 0.8,
    w: 21,
    h: 19,
    note: "The ecclesiastical power, held in the left hand — and held by the same figure who holds the sword. That is the argument of Parts III and IV in a single gesture: there is no second, spiritual sovereign standing beside the civil one. The right column of panels belongs to it.",
    href: "/concepts/church/",
    hrefLabel: "Church",
  },
  {
    id: "country",
    title: "The country",
    x: 0.5,
    y: 29.5,
    w: 99,
    h: 12,
    note: "Cultivated hills, hedged fields, villages with their churches, roads with nobody fleeing along them. This is what protection buys: the commodious living that the state of nature makes impossible, spread out under the giant who guarantees it.",
    href: "/themes/commodious-living/",
    hrefLabel: "Commodious living",
  },
  {
    id: "town",
    title: "The town",
    x: 24,
    y: 41.5,
    w: 75,
    h: 8,
    note: "A walled town at peace, its cathedral the tallest thing in it. The streets are all but empty: a few sentries, and near the cathedral two beaked figures usually read as plague doctors — order, but an order that is kept, not given.",
  },
  {
    id: "castle",
    title: "The castle",
    side: "civil",
    x: 0.8,
    y: 49.4,
    w: 26.7,
    h: 8.3,
    note: "A fortress on its hill: the strong point of the civil power. Every panel on this side has its double straight across the page — the castle's is the church.",
  },
  {
    id: "church",
    title: "The church",
    side: "church",
    x: 71.3,
    y: 49.4,
    w: 27.4,
    h: 8.3,
    note: "The church building, set opposite the castle: the ecclesiastical strong point, drawn the way the fortress is drawn. The pairing runs down both columns — each power has the same equipment in its own kind.",
  },
  {
    id: "coronet",
    title: "The coronet",
    side: "civil",
    x: 0.8,
    y: 58.2,
    w: 26.7,
    h: 6.3,
    note: "A crown: civil honour, the value the sovereign power sets on a man. Titles of honour are its coin, and Chapter 10 prices them. Its double opposite is the mitre.",
    href: "/concepts/honour/",
    hrefLabel: "Honour",
  },
  {
    id: "mitre",
    title: "The mitre",
    side: "church",
    x: 71.3,
    y: 58.2,
    w: 27.4,
    h: 6.3,
    note: "A bishop's mitre, opposite the coronet: ecclesiastical honour, rank and dignity in the church's kind. The symmetry is the point — both are marks of power over men, whatever else they claim to be.",
  },
  {
    id: "cannon",
    title: "The cannon",
    side: "civil",
    x: 0.8,
    y: 64.9,
    w: 26.7,
    h: 6.5,
    note: "Artillery: the civil power's final argument. Across the page, the church's artillery answers it — a thunderbolt.",
    href: "/themes/war/",
    hrefLabel: "War",
  },
  {
    id: "thunderbolt",
    title: "The thunderbolts",
    side: "church",
    x: 71.3,
    y: 64.9,
    w: 27.4,
    h: 6.5,
    note: "Forked lightning: excommunication, the church's cannon. To be cast out — aposunagogon poiein, put out of the meeting — was the heaviest ordnance the ecclesiastical power possessed, and Part III spends some care disarming it.",
    href: "/greek/#aposunagogon-poiein",
    hrefLabel: "In the Greek glossary",
  },
  {
    id: "arms",
    title: "The weapons",
    side: "civil",
    x: 0.8,
    y: 71.8,
    w: 26.7,
    h: 12.7,
    note: "A trophy of arms: muskets, pikes, colours, a drum. The instruments an actual war is fought with, stacked and ready.",
    href: "/themes/war/",
    hrefLabel: "War",
  },
  {
    id: "forks",
    title: "The weapons of logic",
    side: "church",
    x: 71.3,
    y: 71.8,
    w: 27.4,
    h: 12.7,
    note: "The church's arsenal, and the engraving's best joke: pronged forks labelled Syllogisme, Spirituall and Temporall, Reall and Intentionall, Directe and Indirecte, and — the two-horned fork — Di-lem-ma. The schools' distinctions, sharpened for use. Part IV is the long version of this panel.",
    href: "/concepts/kingdom-of-darkness/",
    hrefLabel: "The Kingdom of Darkness",
  },
  {
    id: "battle",
    title: "The battle",
    side: "civil",
    x: 0.8,
    y: 85,
    w: 26.7,
    h: 13.2,
    note: "A cavalry engagement, smoke and lances: war itself, the condition the whole apparatus above exists to hold off, and the one England was in while the plate was being cut.",
    href: "/context/the-english-civil-war/",
    hrefLabel: "The English civil war",
  },
  {
    id: "court",
    title: "The disputation",
    side: "church",
    x: 71.3,
    y: 85,
    w: 27.4,
    h: 13.2,
    note: "An ecclesiastical court in session, divines ranged on their benches: the battle's double. A war carried on in argument — and, Hobbes would add, the kind that starts the other kind.",
    href: "/themes/religion/",
    hrefLabel: "Religion",
  },
  {
    id: "title",
    title: "The title",
    x: 28.5,
    y: 49.4,
    w: 41.5,
    h: 36.5,
    note: "The title on a hanging curtain, and the diagram in words: the Matter, Forme and Power of a Common-wealth Ecclesiasticall and Civil. One adjective for each column of panels, both governed by the figure above.",
    href: "/contents/",
    hrefLabel: "Contents",
  },
  {
    id: "imprint",
    title: "The imprint",
    x: 28.5,
    y: 86.2,
    w: 41.5,
    h: 12,
    note: "London, printed for Andrew Crooke, 1651. Crooke sold the book at the Green Dragon in St Paul's Churchyard; the engraving itself was made in Paris, by Abraham Bosse, with Hobbes looking over his shoulder.",
  },
];
