version: "0.5"

processes:
  install:
    command: bun install
    availability:
      restart: "no"

  site:
    command: bun run dev --port 3000
    depends_on:
      install:
        condition: process_completed_successfully
    readiness_probe:
      http_get:
        host: localhost
        port: 3000
        path: /
      initial_delay_seconds: 2
      period_seconds: 2

  storybook:
    command: bun run storybook
    depends_on:
      install:
        condition: process_completed_successfully
    readiness_probe:
      http_get:
        host: localhost
        port: 6006
        path: /
      initial_delay_seconds: 5
      period_seconds: 2
