/**
 * Checks every internal link in the built site: that the page it points to
 * exists, and that the fragment it names is an id on that page.
 *
 * Run against `dist/` after a build (`bun run check:links`). External links
 * are listed but not fetched — the point is to catch the links this repo can
 * actually break, which is nearly all of them, since the site is one dense
 * web of cross-references generated by half a dozen rehype plugins.
 *
 * Written as a script here rather than pulling in htmltest so that it runs the
 * same way in the dev shell and in CI, which has bun and nothing else. Plain
 * JS, like the other node-side helpers in src/lib.
 */
import { readdirSync, readFileSync, existsSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const DIST = "dist";

/** Every .html file under dist, as paths relative to the working directory. */
function pages(dir = DIST) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) out.push(...pages(path));
    else if (name.endsWith(".html")) out.push(path);
  }
  return out;
}

/** The URL path a built file is served at: dist/themes/law/index.html → /themes/law/ */
const urlOf = (file) =>
  "/" + file.slice(DIST.length + 1).replace(/index\.html$/, "").replace(/\.html$/, "");

// Whitespace before the attribute, so Alpine bindings like x-bind:href="href"
// are not mistaken for links.
const ATTR = /\s(?:href|src)="([^"]*)"/g;
const ID = /\sid="([^"]+)"/g;

const ids = new Map();
const files = pages();
for (const file of files) {
  const html = readFileSync(file, "utf8");
  ids.set(urlOf(file), new Set([...html.matchAll(ID)].map((m) => m[1])));
}

/** Where a link lands, as a URL path, or null if it leaves the site. */
function target(from, href) {
  if (/^(https?:|mailto:|tel:|data:|#)/.test(href) || href === "") return null;
  const path = href.split("#")[0].split("?")[0];
  if (!path) return null;
  return path.startsWith("/") ? path : resolve(from, path);
}

/** The file that serves a URL path, or null if nothing does. */
function fileFor(url) {
  const base = join(DIST, decodeURIComponent(url));
  for (const candidate of [base, `${base}.html`, join(base, "index.html")]) {
    if (existsSync(candidate) && statSync(candidate).isFile()) return candidate;
  }
  return null;
}

const broken = [];
const noSlash = [];
let checked = 0;

for (const file of files) {
  const page = urlOf(file);
  const html = readFileSync(file, "utf8");
  for (const [, raw] of html.matchAll(ATTR)) {
    const href = raw.replace(/&amp;/g, "&");
    const fragment = href.includes("#") ? href.slice(href.indexOf("#") + 1) : "";

    // Same-page fragment.
    if (href.startsWith("#")) {
      checked++;
      if (fragment && !ids.get(page)?.has(decodeURIComponent(fragment))) {
        broken.push(`${page} → ${href} (no such id on this page)`);
      }
      continue;
    }

    const url = target(page, href);
    if (url === null) continue;
    checked++;

    const served = fileFor(url);
    if (!served) {
      broken.push(`${page} → ${href} (no page at ${url})`);
      continue;
    }
    if (!url.endsWith("/") && !url.includes(".")) noSlash.push(`${page} → ${href}`);
    if (fragment) {
      const has = ids.get(urlOf(served))?.has(decodeURIComponent(fragment));
      if (!has) broken.push(`${page} → ${href} (no id "${fragment}" on ${url})`);
    }
  }
}

const plural = (n, one) => `${n} ${one}${n === 1 ? "" : "s"}`;
console.log(`[links] ${plural(files.length, "page")}, ${plural(checked, "internal link")} checked`);
if (noSlash.length) {
  console.log(`[links] ${plural(noSlash.length, "link")} without a trailing slash:`);
  for (const l of noSlash.slice(0, 20)) console.log(`  ${l}`);
}
if (broken.length) {
  console.error(`[links] ${plural(broken.length, "broken link")}:`);
  for (const l of broken) console.error(`  ${l}`);
  process.exit(1);
}
console.log("[links] all good");
